import { createFileRoute } from "@tanstack/react-router";
import { Bar, BarChart, CartesianGrid, Cell, Pie, PieChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import { RefreshCw } from "lucide-react";
import { useAnalytics } from "@/lib/api";
export const Route = createFileRoute("/analytics")({ component: AnalyticsPage });
const COLORS = ["oklch(0.55 0.21 27)", "oklch(0.68 0.14 70)", "oklch(0.55 0.13 155)"];
function AnalyticsPage() { const { data, isLoading, error, refetch, isFetching } = useAnalytics(); if (isLoading) return <State label="Loading analytics…" />; if (error || !data) return <State label="Analytics could not be loaded." retry={refetch} />; return <div className="p-4 lg:p-8"><div className="flex items-start justify-between"><div><h1 className="text-2xl font-semibold">Analytics</h1><p className="mt-1 text-sm text-muted-foreground">Operational view of classification and resolution performance.</p></div><button onClick={() => refetch()} disabled={isFetching} className="rounded-full border border-border p-2"><RefreshCw className={`size-4 ${isFetching ? "animate-spin" : ""}`} /></button></div><div className="mt-6 grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{[{ label: "Resolution rate", value: `${data.resolution_rate}%` }, { label: "Resolved", value: data.resolved }, { label: "Open cases", value: data.open }, { label: "Rejected", value: data.rejected }].map((stat) => <div key={stat.label} className="rounded-2xl border border-border bg-card p-5 shadow-e1"><p className="text-xs text-muted-foreground">{stat.label}</p><p className="mt-1 text-3xl font-semibold">{stat.value}</p></div>)}</div><div className="mt-6 grid gap-6 xl:grid-cols-2"><Chart title="Petitions by department"><BarChart data={data.by_department}><CartesianGrid strokeDasharray="3 3" vertical={false} /><XAxis dataKey="value" tickLine={false} axisLine={false} fontSize={11} /><YAxis allowDecimals={false} tickLine={false} axisLine={false} fontSize={11} /><Tooltip /><Bar dataKey="count" fill="oklch(0.53 0.184 261)" radius={[6, 6, 0, 0]} /></BarChart></Chart><Chart title="Priority distribution"><PieChart><Pie data={data.by_priority} dataKey="count" nameKey="value" innerRadius={60} outerRadius={95} paddingAngle={3}>{data.by_priority.map((_, index) => <Cell key={index} fill={COLORS[index % COLORS.length]!} />)}</Pie><Tooltip /></PieChart></Chart><Chart title="Petition status" className="xl:col-span-2"><BarChart data={data.by_status}><CartesianGrid strokeDasharray="3 3" vertical={false} /><XAxis dataKey="value" tickLine={false} axisLine={false} fontSize={11} /><YAxis allowDecimals={false} tickLine={false} axisLine={false} fontSize={11} /><Tooltip /><Bar dataKey="count" fill="oklch(0.55 0.13 155)" radius={[6, 6, 0, 0]} /></BarChart></Chart></div></div>; }
function Chart({ title, children, className = "" }: { title: string; children: React.ReactElement; className?: string }) { return <div className={`rounded-2xl border border-border bg-card p-6 shadow-e1 ${className}`}><h2 className="text-sm font-semibold">{title}</h2><div className="mt-4 h-72"><ResponsiveContainer width="100%" height="100%">{children}</ResponsiveContainer></div></div>; }
function State({ label, retry }: { label: string; retry?: () => void }) { return <div className="p-16 text-center text-sm text-muted-foreground"><p>{label}</p>{retry && <button onClick={() => retry()} className="mt-3 text-primary underline">Try again</button>}</div>; }
