import { createFileRoute, Link } from "@tanstack/react-router";
import { Inbox, Clock3, Brain, AlertTriangle, Send, ArrowUpRight, Sparkles, RefreshCw } from "lucide-react";
import { useDashboard } from "@/lib/api";
import { PriorityBadge, StatusBadge } from "@/components/petition/badges";

export const Route = createFileRoute("/")({ component: DashboardPage });

function DashboardPage() {
  const { data, isLoading, error, refetch, isFetching } = useDashboard();
  if (isLoading) return <PageState label="Loading dashboard data…" />;
  if (error || !data) return <PageState label="Dashboard data could not be loaded." retry={refetch} />;
  const stats = [
    { label: "Total petitions", value: data.total, icon: Inbox, tone: "bg-info-soft text-accent-foreground" },
    { label: "Pending", value: data.pending, icon: Clock3, tone: "bg-muted text-muted-foreground" },
    { label: "Analysed by AI", value: data.analysed, icon: Brain, tone: "bg-info-soft text-accent-foreground" },
    { label: "High priority", value: data.high_priority, icon: AlertTriangle, tone: "bg-danger-soft text-destructive" },
    { label: "Forwarded", value: data.forwarded, icon: Send, tone: "bg-success-soft text-success" },
  ];
  const maxLoad = Math.max(1, ...data.by_department.map((department) => department.count));
  return <div className="animate-rise p-4 lg:p-8">
    <div className="flex flex-wrap items-end justify-between gap-4"><div><h1 className="text-2xl font-semibold">Grievance Cell Dashboard</h1><p className="mt-1 text-sm text-muted-foreground">Petitions arriving by email are classified automatically before officer review.</p></div><div className="flex gap-2"><button onClick={() => refetch()} className="inline-flex items-center gap-2 rounded-full border border-border bg-card px-4 py-2.5 text-sm font-medium" disabled={isFetching}><RefreshCw className={`size-4 ${isFetching ? "animate-spin" : ""}`} /> Refresh</button><Link to="/inbox" className="inline-flex items-center gap-2 rounded-full bg-primary px-5 py-2.5 text-sm font-medium text-primary-foreground shadow-e1">Open inbox <ArrowUpRight className="size-4" /></Link></div></div>
    <div className="mt-6 grid gap-4 sm:grid-cols-2 xl:grid-cols-5">{stats.map((stat) => <div key={stat.label} className="rounded-2xl border border-border bg-card p-5 shadow-e1"><span className={`inline-flex size-9 items-center justify-center rounded-full ${stat.tone}`}><stat.icon className="size-[18px]" /></span><p className="mt-3 text-3xl font-semibold">{stat.value}</p><p className="text-xs text-muted-foreground">{stat.label}</p></div>)}</div>
    <div className="mt-6 grid gap-6 xl:grid-cols-[minmax(0,1fr)_360px]"><section className="rounded-2xl border border-border bg-card shadow-e1"><div className="flex items-center justify-between border-b border-border px-6 py-4"><h2 className="text-sm font-semibold">Recent activity</h2><Link to="/inbox" className="text-xs font-medium text-primary hover:underline">View all</Link></div><div className="divide-y divide-border">{data.recent.length ? data.recent.map((petition) => <PetitionRow key={petition.id} petition={petition} />) : <Empty label="No petitions have been received yet." />}</div></section><div className="space-y-6"><section className="rounded-2xl border border-border bg-card p-6 shadow-e1"><h2 className="flex items-center gap-2 text-sm font-semibold"><AlertTriangle className="size-4 text-destructive" /> Needs attention</h2><div className="mt-4 space-y-3">{data.urgent.length ? data.urgent.map((petition) => <Link key={petition.id} to="/petitions/$petitionId" params={{ petitionId: String(petition.id) }} className="block rounded-xl bg-danger-soft/60 p-3"><p className="line-clamp-2 text-sm font-medium">{petition.subject}</p><p className="mt-1 text-[11px] text-muted-foreground">{petition.status}</p></Link>) : <p className="text-sm text-muted-foreground">No open high-priority petitions.</p>}</div></section><section className="rounded-2xl border border-border bg-card p-6 shadow-e1"><h2 className="flex items-center gap-2 text-sm font-semibold"><Sparkles className="size-4 text-primary" /> Department load</h2><div className="mt-4 space-y-3">{data.by_department.length ? data.by_department.slice(0, 5).map((department) => <div key={department.value}><div className="flex justify-between text-xs"><span className="font-medium">{department.value}</span><span className="text-muted-foreground">{department.count}</span></div><div className="mt-1 h-1.5 rounded-full bg-muted"><div className="h-full rounded-full bg-primary" style={{ width: `${department.count / maxLoad * 100}%` }} /></div></div>) : <p className="text-sm text-muted-foreground">No AI department classifications yet.</p>}</div></section></div></div>
  </div>;
}
function PetitionRow({ petition }: { petition: NonNullable<ReturnType<typeof useDashboard>["data"]>["recent"][number] }) { return <Link to="/petitions/$petitionId" params={{ petitionId: String(petition.id) }} className="ripple-row flex items-center gap-4 px-6 py-3.5 hover:bg-muted/60"><span className="min-w-0 flex-1"><span className="block truncate text-sm font-medium">{petition.subject}</span><span className="block text-xs text-muted-foreground">#{petition.id} · {petition.analysis?.department_code ?? "Awaiting classification"}</span></span>{petition.analysis && <PriorityBadge priority={petition.analysis.priority} />}<StatusBadge status={petition.status} /></Link>; }
function PageState({ label, retry }: { label: string; retry?: () => void }) { return <div className="p-16 text-center text-sm text-muted-foreground"><p>{label}</p>{retry && <button onClick={() => retry()} className="mt-3 text-primary underline">Try again</button>}</div>; }
function Empty({ label }: { label: string }) { return <p className="px-6 py-10 text-center text-sm text-muted-foreground">{label}</p>; }
