services:
  - type: web
    name: mantriOS-backend
    runtime: python-3.11
    buildCommand: pip install -r backend/requirements.txt
    startCommand: gunicorn app.main:app --workers 4 --worker-class uvicorn.workers.UvicornWorker
    envVars:
      - key: PYTHON_VERSION
        value: 3.11