/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as DepartmentsRouteImport } from './routes/departments'
import { Route as InboxRouteImport } from './routes/inbox'
import { Route as PetitionsPetitionIdRouteImport } from './routes/petitions.$petitionId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const DepartmentsRoute = DepartmentsRouteImport.update({
  id: '/departments',
  path: '/departments',
  getParentRoute: () => rootRouteImport,
} as any)
const InboxRoute = InboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => rootRouteImport,
} as any)
const PetitionsPetitionIdRoute = PetitionsPetitionIdRouteImport.update({
  id: '/petitions/$petitionId',
  path: '/petitions/$petitionId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/departments': typeof DepartmentsRoute
  '/inbox': typeof InboxRoute
  '/petitions/$petitionId': typeof PetitionsPetitionIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/departments': typeof DepartmentsRoute
  '/inbox': typeof InboxRoute
  '/petitions/$petitionId': typeof PetitionsPetitionIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/departments': typeof DepartmentsRoute
  '/inbox': typeof InboxRoute
  '/petitions/$petitionId': typeof PetitionsPetitionIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/analytics' | '/departments' | '/inbox' | '/petitions/$petitionId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/analytics' | '/departments' | '/inbox' | '/petitions/$petitionId'
  id:
    | '__root__'
    | '/'
    | '/analytics'
    | '/departments'
    | '/inbox'
    | '/petitions/$petitionId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnalyticsRoute: typeof AnalyticsRoute
  DepartmentsRoute: typeof DepartmentsRoute
  InboxRoute: typeof InboxRoute
  PetitionsPetitionIdRoute: typeof PetitionsPetitionIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/departments': {
      id: '/departments'
      path: '/departments'
      fullPath: '/departments'
      preLoaderRoute: typeof DepartmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inbox': {
      id: '/inbox'
      path: '/inbox'
      fullPath: '/inbox'
      preLoaderRoute: typeof InboxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/petitions/$petitionId': {
      id: '/petitions/$petitionId'
      path: '/petitions/$petitionId'
      fullPath: '/petitions/$petitionId'
      preLoaderRoute: typeof PetitionsPetitionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnalyticsRoute: AnalyticsRoute,
  DepartmentsRoute: DepartmentsRoute,
  InboxRoute: InboxRoute,
  PetitionsPetitionIdRoute: PetitionsPetitionIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
