import { Building2 } from "lucide-react";

export function DepartmentEmptyState() {
  return (
    <div className="flex flex-col items-center justify-center rounded-2xl border border-slate-200 bg-white p-12 text-center shadow-xs my-8">
      <div className="mx-auto mb-4 flex size-12 items-center justify-center rounded-2xl bg-slate-100 text-slate-500">
        <Building2 className="size-6" />
      </div>

      <h2 className="text-base font-bold text-slate-900">No department data available</h2>

      <p className="mt-1 max-w-md text-xs text-slate-500">
        No department classifications have been generated by AI analysis for incoming petitions yet.
      </p>
    </div>
  );
}
